# help and print Instructions

In [3]:
help(int)#Use help

Help on class int in module builtins:

class int(object)
 |  int([x]) -> integer
 |  int(x, base=10) -> integer
 |  
 |  Convert a number or string to an integer, or return 0 if no arguments
 |  are given.  If x is a number, return x.__int__().  For floating point
 |  numbers, this truncates towards zero.
 |  
 |  If x is not a number or if base is given, then x must be a string,
 |  bytes, or bytearray instance representing an integer literal in the
 |  given base.  The literal can be preceded by '+' or '-' and be surrounded
 |  by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
 |  Base 0 means to interpret the base from the string as an integer literal.
 |  >>> int('0b100', base=0)
 |  4
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __and__(self, value, /)
 |      Return self&value.
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __ceil__(...)
 |      Ceiling of

In [13]:
# (ESC+L) will enumerate the lines of code
# (ctrl+?) will comment and uncomment things
# (ctrl+]) will help to indent several lines of codes at once
# (shift + enter) will execute the code inside each cell                                    
"""
These are also comments
You can write comments in several lines
This is cool!
"""
print("*************")
print("** ------- **") 
print("**|       |**") 
print("**|       |**")
print("**|       |**")
print("**|       |**")
print("**|       |**")
print("**|       |**")
print("**|       |**")
print("**|       |**")
print("** ------- **")
print("*************")

*************
** ------- **
**|       |**
**|       |**
**|       |**
**|       |**
**|       |**
**|       |**
**|       |**
**|       |**
** ------- **
*************


In [53]:
# ASCII representation
# Each character is represented by a number between 0 and 256 stored in an 8 bit memory
# We can use ord() function to find the numeric value of a simple ASCII character
print(ord("H"))
print(ord("*"))
print(ord("h"))
print(ord("\n")) # Remember that new line is a single character

72
42
104
10


In [56]:
# Unicode
# UTF-8 is a particular (the most popular) way of encoding Unicode
# UTF-8 is a variable length encoding with a minimum of 8 bits per character. Characters with higher code points will take up to 32 bits. 

# In python3, all strings are unicode
x = "你好"
print(type(x))

<class 'str'>


# Variables

In [15]:
character_name = "Reza"
character_age = "25"
brother_age = 18
income = 30000000
isMale = True
isRich = False
print("There was a guy named " + character_name +",")
print("and his age is " + character_age + ".")
print("His income is " + str(income) + ".")# We cannot use + for int concatenation
print("His brother is ", brother_age, ".")
print("His brother is " + str(brother_age) + ".")

There was a guy named Reza,
and his age is 21.
His income is 6165135.
His brother is  18 .
His brother is 18.


# Strings

In [17]:
# In python 3, all strings are unicode. We can show all characters we wish
# Strings are immutable
print("Welcome to school\n")
print("my name is\n Reza.")
print("This \"character\" is important.")

Welcome to school

my name is
 Reza.
This "character" is important.


In [165]:
fruit = "banana"
print(fruit[1])

a


In [166]:
x = 3
print(fruit[x-1])

n


In [167]:
print(fruit[6]) # This will return an error, because such index does not exist in fruit string variable

IndexError: string index out of range

In [177]:
# using "in" as a logical operator
print("b" in "apple")
print("b" in fruit)
print("nan" in fruit)
print("m" in fruit)

False
True
True
False


In [183]:
print(fruit.find("na"))# The first "na" it encounters

2


In [184]:
print(fruit.find("z"))#It shows flag -1 if nothing is found

-1


In [185]:
print(fruit.capitalize())

Banana


In [181]:
Greet = "HELLO BOB!"
print(Greet.lower())# The original Greet will not change, we just create a copy
print(Greet)

hello bob!
HELLO BOB!


In [182]:
dir(Greet) #shows methods in class str

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',


In [18]:
Number = '1000'
print(int(Number)+1)

1001


In [19]:
nam = input('who are you? ')

who are you? Reza


In [3]:
print(nam)

Reza


In [20]:
TEXT1 = "He is a rich guy. He is from Finland. He helps everyone to be happy."
TEXT2 = "My name is Reza!"

print(TEXT1)

He is a rich guy. He is from Finland. He helps everyone to be happy.


In [21]:
print(TEXT1.isupper())

False


In [23]:
print(TEXT1.upper())#Makes every letter capital

HE IS A RICH GUY. HE IS FROM FINLAND. HE HELPS EVERYONE TO BE HAPPY.


In [25]:
print(TEXT1.upper().isupper())
print(TEXT2.isupper())

True
False


In [29]:
print(TEXT1.count("He"))
print(TEXT1.count("he"))
print(TEXT1.count("ch"))

3
1
1


In [31]:
Length = len(TEXT1) #len() function returns the number of characters in the string
print(Length)

A = [11, 22, 33, 44, 50]
Length2 = len(A) #len() function returns the number of items in an object. 
print(Length2)

68
5


In [33]:
if len(TEXT1)>len(TEXT2):
    print(TEXT1)
else:
    print(TEXT2)

He is a rich guy. He is from Finland. He helps everyone to be happy.


In [37]:
if len(TEXT1)<len(TEXT2):
    print(TEXT1, "\ncharacters = ", len(TEXT1))
else:
    print(TEXT2, "\ncharacters = ", len(TEXT2))

Hi Reza! 
characters =  8


In [40]:
print(TEXT1[0]) # We can use brackets to access specific characters
print(TEXT1[1]) # Python starts indexing the characters in a string from zero (0)
print(TEXT1[2])
print(TEXT1[3])
print(TEXT1[4])

H
e
 
i
s


In [41]:
Indx = TEXT1.index("!") # If character is not found, it will show an error
print(Indx)

ValueError: substring not found

In [42]:
Indx = TEXT2.index("!") # If character is not found, it will show an error
print(Indx)

7


In [186]:
phrase1 = "English literature is my favorite subject at school!"

print(phrase1.replace("English literature", "Computer science"))#This is a copy. The original would not change!!! # It replaces all of the instances that exist!!!
print(phrase1)

Computer science is my favorite subject at school!
English literature is my favorite subject at school!


In [168]:
mystring = "Hong Kong"
index = 0

while index < len(mystring):
    print(index, mystring[index])
    index = index + 1

0 H
1 o
2 n
3 g
4  
5 K
6 o
7 n
8 g


In [171]:
for letter in mystring:
    print(letter)

H
o
n
g
 
K
o
n
g


In [170]:
counter = 0
for letter in mystring:
    if letter == "o":
        counter += 1
print("Number of o: ", counter)

Number of o:  2


In [173]:
# slicing
print(mystring[0:7])

Hong Ko


In [188]:
Message = "         Hello Bob!           "
# How can we get rid of the white spaces?
print(Message.lstrip()) # left strip # all of these strip instructions just make a copy and does not change the original Message
print(Message.rstrip()) # right strip
print(Message.strip())# strip

Hello Bob!           
         Hello Bob!
Hello Bob!


In [191]:
Message2 = "Tomorrow is Asal's birthday!"
print(Message2.startswith("To"))
print(Message2.startswith("to"))

True
False


In [196]:
email = "rhadimogavi@connect.ust.hk Mon Jan 2017 16:30:20"
atpos = email.find("@")
print(atpos)
sppos = email.find(" ", atpos) #atpos is from wehere we start searching
print(sppos)
host = email[atpos+1:sppos]
print(host) # This is how we extract data from a string

11
26
connect.ust.hk


In [40]:
#Split breaks a string into parts and produces a list of strings. We think of these as words. We can access a particular world or loop through all words
p1 = "I am very pleased to inform you that you are admitted to HKUST. I hope we can meet you more."
wlist = p1.split()
print(wlist)

count = 0
for word in wlist:
    if word == "I":
        count += 1
print("I is used", count, "times.")

['I', 'am', 'very', 'pleased', 'to', 'inform', 'you', 'that', 'you', 'are', 'admitted', 'to', 'HKUST.', 'I', 'hope', 'we', 'can', 'meet', 'you', 'more.']
I is used 2 times.


In [43]:
# We can tell python to split based on another character. For example a comma
p2 = "20,32,40,50,60"
nlist = p2.split(",")
print(nlist)

['20', '32', '40', '50', '60']


In [45]:
# The double split pattern
p3 = "From engineer.reza84@gmail.com SAT 2017 2:30:12"

fsplit = p3.split()
print(fsplit[1])

ssplit = fsplit[1].split("@")
print(ssplit[1])

engineer.reza84@gmail.com
gmail.com


# Numbers

In [46]:
print(36)
print(-36.7)
print(3 + 4 * 2 - 1)
print(11/2)
print(11 % 3) # This operator is called mod and gives the remainder value
Wage = 60000000
print(Wage)
number1 = -354.21
print(abs(number1))
print(pow(3, 2))#3^2
print(max(2, 7))
print(min(2, 7))
print(round(3.2))
print(round(3.9))

36
-36.7
10
5.5
2
60000000
354.21
9
7
2
3
4


In [49]:
print(pow(2, 5))#2^5

32


In [54]:
number1 = "59"
number2 = "59.00"
number3 = "59.10"

print(int(number1) + 11)
print(float(number1) + 11)

# print(int(number2) + 11) #This line of code is wrong
print(float(number2) + 11)

# print(int(number3) + 11)
print(float(number3) + 11)

70
70.0
70.0
70.1


In [156]:
print(2**4)
a = 3
b = 2
print(a**b)
print(pow(3, 3))

16
9
27


In [77]:
from math import * # more math functions. math here is a module
print(floor(3.7))
print(ceil(3.7))
print(sqrt(36))

3
4
6.0


# Lists

In [26]:
# We can create an empty list like below:
emlist = list()
print(emlist)

# We can append to our list:
emlist.append("a")
print(emlist)
# Lists maintain order

[]
['a']


In [34]:
alphlist = ["I", "J", "K", "A", "B", "C", "D", "H", "L", "M", "N", "O", "P", "Q", "V", "W", "X", "Y", "Z", "R", "S", "E", "F", "G", "T", "U"]
# list is a mutable (changeable object)
alphlist.sort()
print(alphlist)

# How many items are there in the list?
print("We have", len(alphlist), "alphabet letters in our list.")

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
We have 26 alphabet letters in our list.


In [29]:
students = ["Sam", "Reza", "James", "John", "Ann", "Ehsan", "Pedram"]
List1 = ["Sam", 12, True] #Lists can include anything! Really anything!

In [31]:
print(students)
print("Reza" in students) # True or False. # Is Reza in students?
print("Habib" not in students)
print(List1)

['Sam', 'Reza', 'James', 'John', 'Ann', 'Ehsan', 'Pedram']
True
True
['Sam', 12, True]


In [8]:
# Getting access to the items in a list
students = ["Sam", "Reza", "James", "John", "Ann", "Ehsan", "Pedram"]
print(students[4])
print(students[-1])
print(students[-5])
print(students[2])

Ann
Pedram
James
James


In [57]:
# Now let's learn about slicing~
# for selecting a portion:
A = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 140, 160, 180, 200, 210]

In [58]:
print(A[1:7])

[20, 30, 40, 50, 60, 70]


In [59]:
print(A[1:7:2])

[20, 40, 60]


In [61]:
print(A[7:1:-1])

[80, 70, 60, 50, 40, 30]


In [63]:
print(A[::-1])

[210, 200, 180, 160, 140, 120, 110, 100, 90, 80, 70, 60, 50, 40, 30, 20, 10]


In [64]:
print(A[3:])

[40, 50, 60, 70, 80, 90, 100, 110, 120, 140, 160, 180, 200, 210]


In [65]:
print(A[2:5])

[30, 40, 50]


In [66]:
print(students[2:5:2])

['James', 'Ann']


In [10]:
#Modify values inside lists:
students[2] = "Karen"
print(students[2])
print(students)

Karen
['Sam', 'Reza', 'Karen', 'John', 'Ann', 'Ehsan', 'Pedram']


In [38]:
numlist = list()
while True:
    value = input("Please enter a number: ")
    if value == "done":
        break
    numlist.append(float(value))
    
print("The average value is:", sum(numlist)/len(numlist))

Please enter a number: 2
Please enter a number: 3
Please enter a number: done
The average value is: 2.5


# List Functions

In [142]:
students = ["Sam", "Reza", "James", "John", "Ann", "Ehsan", "Pedram", "James"]
grades = [80, 95, 79, 85, 96, 99, 100, 65]

In [143]:
print(students)
print(grades)

['Sam', 'Reza', 'James', 'John', 'Ann', 'Ehsan', 'Pedram', 'James']
[80, 95, 79, 85, 96, 99, 100, 65]


In [144]:
students.extend(grades)#add another list to the end of the list
print(students)

['Sam', 'Reza', 'James', 'John', 'Ann', 'Ehsan', 'Pedram', 'James', 80, 95, 79, 85, 96, 99, 100, 65]


In [145]:
students.append(88)#add a single element to the end of the list
print(students)

['Sam', 'Reza', 'James', 'John', 'Ann', 'Ehsan', 'Pedram', 'James', 80, 95, 79, 85, 96, 99, 100, 65, 88]


In [146]:
students.insert(1, "Bernadette") #add item to a specific position
print(students)

['Sam', 'Bernadette', 'Reza', 'James', 'John', 'Ann', 'Ehsan', 'Pedram', 'James', 80, 95, 79, 85, 96, 99, 100, 65, 88]


In [148]:
studentscopy1 = students #studentcopy1 is exactly the students. If you delete or clear one, the other will also be deleted or cleared 
studentscopy = students.copy()# Please copy a list like this
print(studentscopy)

['Sam', 'Bernadette', 'Reza', 'James', 'John', 'Ann', 'Ehsan', 'Pedram', 'James', 80, 95, 79, 85, 96, 99, 100, 65, 88]


In [149]:
studentscopy.remove("James")#only eliminates the first James
print(studentscopy)

['Sam', 'Bernadette', 'Reza', 'John', 'Ann', 'Ehsan', 'Pedram', 'James', 80, 95, 79, 85, 96, 99, 100, 65, 88]


In [150]:
studentscopy.clear()#This will clear everything on the list. It will give an empty list.
print(studentscopy)

[]


In [151]:
value = students.pop()#pops an element from the end of the list
print(value)
print(students)

88
['Sam', 'Bernadette', 'Reza', 'James', 'John', 'Ann', 'Ehsan', 'Pedram', 'James', 80, 95, 79, 85, 96, 99, 100, 65]


In [152]:
print(studentscopy1)

['Sam', 'Bernadette', 'Reza', 'James', 'John', 'Ann', 'Ehsan', 'Pedram', 'James', 80, 95, 79, 85, 96, 99, 100, 65]


In [154]:
indx = students.index("Reza") #reports the index of the first item found on the list
print(indx)

2


In [156]:
cnt = students.count("James") #counts
cnt1 = students.count("Reza")
print("James: ", cnt, ", Reza: ", cnt1)

James:  2 , Reza:  1


In [157]:
print(grades)

[80, 95, 79, 85, 96, 99, 100, 65]


In [159]:
grades.sort() #ascending order
print(grades)

[65, 79, 80, 85, 95, 96, 99, 100]


In [160]:
grades.reverse() #reverse the order
print(grades)

[100, 99, 96, 95, 85, 80, 79, 65]


In [162]:
grades2 = grades.copy() #make a copy from a list
print(grades2)

[100, 99, 96, 95, 85, 80, 79, 65]


In [163]:
del grades2[3]# delete a specific index from a list #85 is deleted
print(grades2)

[100, 99, 96, 85, 80, 79, 65]


In [164]:
grades2.pop(4)#you can also pop an item based on its index # 80 is popped out
print(grades2)

[100, 99, 96, 85, 79, 65]


# Tuples (Immutable=You cannot change)

In [101]:
# We use Parenthesis () to build tuples
x = (1, 9, 12, 8, 4, 2, 2)
print(x)
print(x[1])
print(len(x))
print(max(x))

(1, 9, 12, 8, 4, 2, 2)
9
7
12


In [158]:
# We cannot sort, reverse, or append to tuples
x1 = (1, 4, 2, 7, 6, 0, 9, 6)
# x1.sort() # does not work!!!!!!!!!!!!!
# x1.append(5) #does not work!!!!!!!!!!!!!
# x1.reverse() # does not work!!!!!!!!!!!!
dir(x1)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'count',
 'index']

In [162]:
print(x1.count(6))
print(x1.index(7))

2
3


In [102]:
for i in x:
    print(i)

1
9
12
8
4
2
2


In [75]:
coordinate = (20, 31)
print(coordinate[1])
locations = [(10, 20), (11, 10), (17, 91)]#A list of tuples
print(locations)
student_id = (13513, 13514, 13533, 13913, 13810)
print(student_id)
type_name = type(student_id) #what is the type? Tupple
print(type_name)

31
[(10, 20), (11, 10), (17, 91)]
(13513, 13514, 13533, 13913, 13810)
<class 'tuple'>


In [103]:
# Tuples and assignment
(a, b, c) = (12, "apple", 20)
print(a)
print(b)
print(c)

12
apple
20


In [105]:
# Tuples are comparable
print((1, 8, 10)<(2, 1, 0)) # It is as if it looks at the most significant digit (left most and then goes down if applicable)
print((0, 2, 100000000)<(0, 5, 3))

True
True


In [106]:
# Sorting "Lists" of Tuples
d = {"a": 20, "m": 12, "d": 8, "b":1000}
print(d.items())

dict_items([('a', 20), ('m', 12), ('d', 8), ('b', 1000)])


In [108]:
print(sorted(d.items())) # Sorted by key order

[('a', 20), ('b', 1000), ('d', 8), ('m', 12)]


In [109]:
# How can we sort by values instead of keys?
tmp = list()
for k,v in d.items():
    tmp.append((v,k))# We create a tuple
    
tmp = sorted(tmp, reverse = True) # Reverse from big to small value
print(tmp)
    

[(1000, 'b'), (20, 'a'), (12, 'm'), (8, 'd')]


# Functions

In [79]:
def greeting():
    print("Hi my lord!")

    
#for calling the function, just call it!
greeting()

Hi my lord!


In [83]:
def plusthree(number):
    return number + 3

print(plusthree(5))    

8


In [84]:
def power(num1, p):
    result = pow(num1, p)
    return result

print(power(2,4))

16


In [199]:
#Let's define a Sigmoid function
import math 

def sigm(x):
    return 1/(1+(1/math.exp(x)))
    
print(sigm(3))
print(sigm(0))
print(sigm(-3))

0.9525741268224334
0.5
0.04742587317756678


# if statement

In [89]:
def comparison(num1, num2):
    if num1 > num2:
        print(str(num1) + " is greater than " + str(num2))
    else:
        print(str(num1) + " is smaller than " + str(num2))

comparison(10, 7)

10 is greater than 7


In [95]:
isMale = True
if isMale == True:   # use == for checking the equality. Reminder: != is checking non-equality.
    print("Hello sir!")
    print("It is great to have you back in our hotel again.")
else:
    print("Hello madam!")
    print("We hope you enjoy your stay in our hotel.")

Hello sir!
It is great to have you back in our hotel again.


In [99]:
isRich = False
isTall = False

if isRich and isTall:
    print("Do you want a cup of coffee?")
elif isRich and not(isTall):
    print("Do you want a glass of water?")
elif isRich or not(isTall):
    print("Do you want a cup of tea?")
else:
    print("Do you want a glass of red wine?")

Do you want a cup of tea?


In [103]:
def yourdrink(isRich, isTall):
    if isRich and isTall:
        text = "Do you want a cup of coffee?"
    elif isRich and not(isTall):
        text = "Do you want a glass of water?"
    elif isRich or not(isTall):
        text = "Do you want a cup of tea?"
    else:
        text = "Do you want a glass of red wine?"
    return text



# let us test our built function
a = False
b = True
print(yourdrink(a, b))

Do you want a glass of red wine?


In [105]:
grade_vec = (2, 3, 7, 6, 10)

if grade_vec[0]!= grade_vec[3]: #!= shows not equal to
    print("We are safe!")
    print(grade_vec[0] + grade_vec[3])
elif grade_vec[0] <= grade_vec[4]:
    print("Nice day!")
    print(grade_vec[0] + grade_vec[4])
else:
    print("I have to go!")

We are safe!
8


In [113]:
num = 18

if num % 2 == 0:
    print("This number is even.")
    if num <= 12:
        print("This number is lower than 12.")
    else:
        print("I do not care!")
else:
    print("This number is odd.")
    if num >= 20:
        print("This number is greater than 20.")

This number is even.
I do not care!


# Dictionary (key and value pairs)

In [52]:
# An empty dictionary
emptdic = {}
print(emptdic)

{}


In [48]:
#Based on HKUST courses
#A dictionary with unique keys:values
CourseName = {
    "ACCT 1610" : "Laws in Society and Business",
    "BIEN 1010" : "Introduction to Biomedical Engineering", 
    "CENG 1500" : "A First Course on Materials Science and Applications",
    "CENG 1600" : "Biotechnology and Its Business Opportunities", 
    "CENG 1700" : "Introduction to Environmental Engineering",
    "CHEM 1002" : "Introduction to Chemistry of Cosmetics",
    "COMP 2711" : "Discrete Mathematical Tools for Computer Science",
    "ECON 2103" : "Principles of Microeconomics"
}
print(CourseName)

{'ACCT 1610': 'Laws in Society and Business', 'BIEN 1010': 'Introduction to Biomedical Engineering', 'CENG 1500': 'A First Course on Materials Science and Applications', 'CENG 1600': 'Biotechnology and Its Business Opportunities', 'CENG 1700': 'Introduction to Environmental Engineering', 'CHEM 1002': 'Introduction to Chemistry of Cosmetics', 'COMP 2711': 'Discrete Mathematical Tools for Computer Science', 'ECON 2103': 'Principles of Microeconomics'}


In [78]:
# Think of dictionaries as unsorted bag of values (We cannot predict the order)
purse = dict() # This will create an empty dictionary named purse
purse["money"] = 12 #(key, vlaue) pair
purse["candy"] = 5
purse["tissues"] = 7
print(purse)

{'money': 12, 'candy': 5, 'tissues': 7}


In [79]:
print(CourseName["COMP 2711"])
print(purse["candy"])

Discrete Mathematical Tools for Computer Science
5


In [80]:
print("candy" in purse) #Checks if this key in my dictionary?
print("coin" in purse)

True
False


In [81]:
# Dictionary contents are mutable. We can change them
purse["candy"] = purse["candy"] + 3
print(purse["candy"])

8


In [82]:
counts = dict()
names = ["Reza", "Jim", "Gloria", "Ann", "Gloria", "Ann", "Ann", "Mary", "Ann", "Reza", "Gloria"]

for name in names:
    if name not in counts:
        counts[name] = 1
    else:
        counts[name] = counts[name] + 1
print(counts)

{'Reza': 2, 'Jim': 1, 'Gloria': 3, 'Ann': 4, 'Mary': 1}


In [84]:
# Get function
purse["bottle"] = purse.get("bottle", 0) + 1 # If key bottle does not exist, create it and set the default value to 1 # It also helps to avoid tracceback error
print(purse)

{'money': 12, 'candy': 8, 'tissues': 7, 'bottle': 2}


In [118]:
print(CourseName.get("COMP 2711")) #The advantage of get is that you can a set a default value if key not found

Discrete Mathematical Tools for Computer Science


In [121]:
print(CourseName.get("COMP 2712"))
print(CourseName.get("COMP 2712", "Reza! The course is not here."))

None
Reza! The course is not here.


In [126]:
#Keys can be numbers as well as long as they are unique
CourseName2 = {
    1610 : "Laws in Society and Business",
    1010 : "Introduction to Biomedical Engineering", 
    1500 : "A First Course on Materials Science and Applications",
    1600 : "Biotechnology and Its Business Opportunities", 
    1700 : "Introduction to Environmental Engineering",
    1002 : "Introduction to Chemistry of Cosmetics",
    2711 : "Discrete Mathematical Tools for Computer Science",
    2103 : "Principles of Microeconomics"
}
print(CourseName2.get(1700))

Introduction to Environmental Engineering


In [128]:
RandomDic = {
    1 : 25,
    2 : 16,
    3 : 90,
    4 : 100
}
print(RandomDic)

{1: 25, 2: 16, 3: 90, 4: 100}


In [129]:
print(RandomDic.get(3))

90


In [87]:
A = {
    1: "Wait, do you see my heart on my sleeve?",
    2: "It's been there for days on end and",
    3: "It's been waiting for you to open up",
    4: "Yours too baby, come on now",
    5: "I'm trying to tell you just how",
    6: "I'd like to hear the words roll out of your mouth finally",
    7: "Say that it's always been me",
    8: "Adele song"
}

for key in A:
    print(key, A[key])

1 Wait, do you see my heart on my sleeve?
2 It's been there for days on end and
3 It's been waiting for you to open up
4 Yours too baby, come on now
5 I'm trying to tell you just how
6 I'd like to hear the words roll out of your mouth finally
7 Say that it's always been me
8 Adele song


# While Loops

In [133]:
i = 1
while i <= 5:
    print(i)
    i += 1 # same as i = i + 1
print("Done with the loop.")

1
2
3
4
5
Done with the loop.


In [146]:
# A simple multiplicaiton table
i = 1
j = 1
result = []
while i <= 10:
    while j <= 10:
        result.append(i*j)
        j = j + 1
    print(result, "\n")
    i += 1
    j = 1
    result.clear()
        

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10] 

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20] 

[3, 6, 9, 12, 15, 18, 21, 24, 27, 30] 

[4, 8, 12, 16, 20, 24, 28, 32, 36, 40] 

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50] 

[6, 12, 18, 24, 30, 36, 42, 48, 54, 60] 

[7, 14, 21, 28, 35, 42, 49, 56, 63, 70] 

[8, 16, 24, 32, 40, 48, 56, 64, 72, 80] 

[9, 18, 27, 36, 45, 54, 63, 72, 81, 90] 

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100] 



# For Loop

In [147]:
for letter in "Hello World!": # We define a variable (here letter) and that changes in every itteration
    print(letter)

H
e
l
l
o
 
W
o
r
l
d
!


In [148]:
classmates = ["Tommy", "Zhenhui", "Meng", "Zack", "Ehsan", "Young"]
for classmate in classmates:
    print(classmate)

Tommy
Zhenhui
Meng
Zack
Ehsan
Young


In [149]:
for index in range(8): #not including 8
    print(index)

0
1
2
3
4
5
6
7


In [150]:
for index in range(2, 8):
    print(index)

2
3
4
5
6
7


In [151]:
classmates = ["Tommy", "Zhenhui", "Meng", "Zack", "Ehsan", "Young"]
for index in range(len(classmates)):
    print(classmates[index])

Tommy
Zhenhui
Meng
Zack
Ehsan
Young


In [152]:
for index in range(5):
    if index == 0:
        print("This is the first iteration.")
    elif index == 1:
        print("This is the second iteration.")
    else:
        print("More than two iterations.")

This is the first iteration.
This is the second iteration.
More than two iterations.
More than two iterations.
More than two iterations.


In [17]:
def powerfunc(num1, num2):
    result = 1
    for index in range(num2):
        result = num1 * result
    return result

powerfunc(3, 4)

81

In [28]:
def me_coder(phrase):
    finalphrase = ""
    for letter in phrase:
        if letter in "asdfASDF":
            finalphrase = finalphrase + "*"
        else:
            finalphrase = finalphrase + letter
    return finalphrase
            
print(me_coder("I could not understand her language."))
print(me_coder("Do you know where to buy some water?"))

I coul* not un*er*t*n* her l*ngu*ge.
*o you know where to buy *ome w*ter?


# 2D Lists and Nested Loops (similar to matrix!)

In [18]:
#rows and columns are exactly the same as what we knew before
matrix = [
    [1, 1, 1, 0, 0],
    [1, 0, 1, 1, 0],
    [0, 1, 0, 1, 0],
    [0, 0, 0, 1, 1]
]

print(matrix[0][1])

1


In [20]:
matrix2 = [
    [109, 119, 111, 100, 801],
    [800, 452, 128, 290, 219],
    [741, 852, 963, 147, 159],
    [357, 267, 313, 218, 401]
]
print(matrix2[2][3])
print(matrix2)

147
[[109, 119, 111, 100, 801], [800, 452, 128, 290, 219], [741, 852, 963, 147, 159], [357, 267, 313, 218, 401]]


In [23]:
grid1 = [
    [109, 119, 111, 100, 801],
    [800, 452, 128, 290, 219],
    [128, 214, "hi"],
    [357, 267, 313, 218, 401]
]
print(grid1[2][2])
# print(grid1[2][3])#This line will give an error since we do not have such element

hi


In [24]:
matrix2 = [
    [109, 119, 111, 100, 801],
    [800, 452, 128, 290, 219],
    [741, 852, 963, 147, 159],
    [357, 267, 313, 218, 401]
]

for row in matrix2:
    print(row)

[109, 119, 111, 100, 801]
[800, 452, 128, 290, 219]
[741, 852, 963, 147, 159]
[357, 267, 313, 218, 401]


In [25]:
matrix2 = [
    [109, 119, 111, 100, 801],
    [800, 452, 128, 290, 219],
    [741, 852, 963, 147, 159],
    [357, 267, 313, 218, 401]
]

for row in matrix2:
    for col in row:
        print(col)

109
119
111
100
801
800
452
128
290
219
741
852
963
147
159
357
267
313
218
401


# Try Except Block (for handling errors)

In [35]:
def oddfinder(num):
    if num % 2 != 0:
        txt = "This is an odd number."
    else:
        txt = "This is an even number."
    return txt

try:
    print(oddfinder(15))
    print(oddfinder(asd)) #wrong input
except: #This type of except is too broad
    print("Something went wrong!")

This is an odd number.
Something went wrong!


In [37]:
def oddfinder(num):
    if num % 2 != 0:
        txt = "This is an odd number."
    else:
        txt = "This is an even number."
    return txt

try:
    print(oddfinder(15))
    print(oddfinder(asd)) #wrong input
except NameError as err: #use tab to see a complete list of except errors #we define err as a variable for error message
    print(err)

This is an odd number.
name 'asd' is not defined


# Reading Files

In [260]:
# A file handle is open for read can be treated as a sequence of strings where each line in the file is a string in the sequence
handle = open("Dummy.txt") # The default mode for opening files is read-only (r)

counter = 0
for lines in handle:
    counter += 1
    print(lines) # This is very simple and we can easily access the data inside our file
print("\nWe have", counter, "lines.")

Josh - CSE department

Ann - Civil department

Tom - CHEM department

Ahmad - BIO department

Shina - ECE department

Rosa - CSE department

Jimmy - MATH department

Hamed - MATH department

Murat - MATH department

Ali - MATH department

We have 10 lines.


In [265]:
"""
open("Dummy.txt", "r") # Opens the file in read-only mode. It is also the default mode for open()
open("Dummy.txt", "w") # Opens in write-only mode. The pointer is placed at the beginning of the file and this will overwrite any existing file with the same name. It will create a new file if one with the same name doesn't exist.
open("Dummy.txt", "a") # Opens a file for appending new information to it. The pointer is placed at the end of the file. A new file is created if one with the same name doesn't exist.
open("Dummy.txt", "r+") # Opens a file for reading and writing, placing the pointer at the beginning of the file.

It is a good practice to close the file at the end
"""
stud_major = open("Dummy.txt", "r")



# We can read the whole file (newlines and all) into a single string
print(stud_major.readable())#This checks if the file is readable
inp = stud_major.read()
print(inp)# This will spit out all the information that exist in the file

print(len(inp))
print(inp[:8])#First eight characters


stud_major.close()#This closes the file 

True
Josh - CSE department
Ann - Civil department
Tom - CHEM department
Ahmad - BIO department
Shina - ECE department
Rosa - CSE department
Jimmy - MATH department
Hamed - MATH department
Murat - MATH department
Ali - MATH department
228
Josh - C


In [16]:
handle2 = open("Dummy2.txt")

for line in handle2:
    ppos = line.find("math") #finds the first math in each line
    print(ppos)
    
handle2.close()

19
36
6
20
16
-1


In [18]:
handle2 = open("Dummy2.txt")

for line in handle2:
    if line.startswith("I"):
        line = line.rstrip() # Because print also adds another \n, this helps to remove the ones from the text
        print(line)
        
handle2.close()

I think we can use math to improve life.
I know learning math is difficult, but learning math is also sweet.
I hope tomorrow is sunny!


In [22]:
handle2 = open("Dummy2.txt")

for line in handle2:
    if not line.startswith("I"):
        continue
       
    line = line.rstrip()
    print(line)
    
handle2.close()

I think we can use math to improve life.
I know learning math is difficult, but learning math is also sweet.
I hope tomorrow is sunny!


In [24]:
handle2 = open("Dummy2.txt")

for line in handle2:
    if not "math" in line:
        continue
    line = line.rstrip()
    print(line)
    
handle2.close()

I think we can use math to improve life.
From tomorrow, I will practice more math.
Every math class has something fun to teach.
We have a very good math teacher.
I know learning math is difficult, but learning math is also sweet.


In [6]:
stud_major = open("Dummy.txt", "r")

print(stud_major.readable())#This checks if the file is readable
print(stud_major.readline())# This reads the first line and puts cursor in the beginning of the second line
print(stud_major.readline())# This reads the second line

stud_major.close()#This closes the file 

True
Josh - CSE department

Ann - Civil department



In [52]:
stud_major = open("Dummy.txt", "r")

print(stud_major.readable())#This checks if the file is readable
# print(stud_major.readlines())#reads all lines at put them into a list
print(stud_major.readlines()[2])#you can access like lists

stud_major.close()#This closes the file 

True
Tom - CHEM department



In [53]:
stud_major = open("Dummy.txt", "r")

for students in stud_major.readlines():
    print(students)

stud_major.close()#This closes the file 

Josh - CSE department

Ann - Civil department

Tom - CHEM department

Ahmad - BIO department

Shina - ECE department

Rosa - CSE department



In [91]:
counts = dict()

handle = open ("Dummy2.txt")

for line in handle:
    words = line.split()
    for word in words:
        counts[word] = counts.get(word,0)+1

print(counts)

{'I': 4, 'think': 1, 'we': 1, 'can': 1, 'use': 1, 'math': 5, 'to': 2, 'improve': 1, 'life.': 1, 'From': 1, 'tomorrow,': 1, 'will': 1, 'practice': 1, 'more': 1, 'math.': 1, 'Every': 1, 'class': 1, 'has': 1, 'something': 1, 'fun': 1, 'teach.': 1, 'We': 1, 'have': 1, 'a': 1, 'very': 1, 'good': 1, 'teacher.': 1, 'know': 1, 'learning': 2, 'is': 3, 'difficult,': 1, 'but': 1, 'also': 1, 'sweet.': 1, 'hope': 1, 'tomorrow': 1, 'sunny!': 1}


In [92]:
print(list(counts))

['I', 'think', 'we', 'can', 'use', 'math', 'to', 'improve', 'life.', 'From', 'tomorrow,', 'will', 'practice', 'more', 'math.', 'Every', 'class', 'has', 'something', 'fun', 'teach.', 'We', 'have', 'a', 'very', 'good', 'teacher.', 'know', 'learning', 'is', 'difficult,', 'but', 'also', 'sweet.', 'hope', 'tomorrow', 'sunny!']


In [93]:
print(counts.keys())

dict_keys(['I', 'think', 'we', 'can', 'use', 'math', 'to', 'improve', 'life.', 'From', 'tomorrow,', 'will', 'practice', 'more', 'math.', 'Every', 'class', 'has', 'something', 'fun', 'teach.', 'We', 'have', 'a', 'very', 'good', 'teacher.', 'know', 'learning', 'is', 'difficult,', 'but', 'also', 'sweet.', 'hope', 'tomorrow', 'sunny!'])


In [94]:
print(counts.values())

dict_values([4, 1, 1, 1, 1, 5, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 1, 1, 1, 1, 1, 1, 1])


In [95]:
print(counts.items()) #produces tuple format

dict_items([('I', 4), ('think', 1), ('we', 1), ('can', 1), ('use', 1), ('math', 5), ('to', 2), ('improve', 1), ('life.', 1), ('From', 1), ('tomorrow,', 1), ('will', 1), ('practice', 1), ('more', 1), ('math.', 1), ('Every', 1), ('class', 1), ('has', 1), ('something', 1), ('fun', 1), ('teach.', 1), ('We', 1), ('have', 1), ('a', 1), ('very', 1), ('good', 1), ('teacher.', 1), ('know', 1), ('learning', 2), ('is', 3), ('difficult,', 1), ('but', 1), ('also', 1), ('sweet.', 1), ('hope', 1), ('tomorrow', 1), ('sunny!', 1)])


In [97]:
bigK = None
bigV = None

for k,v in counts.items(): # k (key) is the first iteration value, and v (value) is the second iteration value. They grow in parallel and make life more convenient to go through a dict
    if bigV is None or bigV<v:
        bigK = k
        bigV = v
print(bigK, "=", bigV) #Most repeated value

math = 5


# Writing to Files

In [2]:
student_major = open("Dummy.txt", "a") #append something at the end of the file 
student_major.write("\nMurat - MATH department")
student_major.close()#Now it is written. You can go and check!

# Regular Expressions

In [168]:
#we need to import the library first
import re

handle = open("Dummy2.txt")

for line in handle:
    if re.search("I", line): # This line searches each line
        print(line)

I think we can use math to improve life.

From tomorrow, I will practice more math.

I know learning math is difficult, but learning math is also sweet.

I hope tomorrow is sunny!


In [173]:
handle = open("Dummy2.txt")

for line in handle:
    if re.search("^I", line): # ^ refers to start of line
        print(line)

I think we can use math to improve life.

I know learning math is difficult, but learning math is also sweet.

I hope tomorrow is sunny!


In [187]:
# The dot character matches any character
# If you add an asterisk character, the character is any number of times
# e.g. ---> ^X.*:  I am looking for strings with X at the beginning, followed by any number of characters and ending with colon :

# We want to extract the expertise of our reviewers
handle = open("Dummy3.txt") 

w = 0
for line in handle:
    if re.search("^Exp.*ise", line):
        w = 1
        continue
        
    if w == 1:
        print(line)
        w = 0

Knowledgeable

Knowledgeable

Passing Knowledge

Expert



In [188]:
# e.g. ---> ^X\S+: --> meaning: find strings that start with X followed by non-white-spacecharacter (\S), one or more time(+), followed by a colon (:)
#\s matches whitespace character, \S matches any non-whitespace character
handle = open("Dummy3.txt") 

# We want to find the order of reviewer comments

W = list()
for line in handle: 
    if re.search("^Rev.*r\s", line):
        W = line.split()
        print(W[1])

2
1
3


In [205]:
# Let's learn about square expression []
#[0-9] means a digit
#[0-9]+ means one or more digits
#[REZA] means one of these characters
#[OAEUI] means one these vowels
#[OAEUI]+ means one or more of these vowels

# re.findall() returns list of zero or more substrings that match the regular expression

A = "ll reviewers found the paper is well-written. R2 highlighted that from R2’s perspective the paper is also sufficiently grounded in the related work. R1 noted that the offered the supplementary materials was very helpful."
print(re.findall("[0-9]+", A))
print(re.findall("R[0-9]", A))

['2', '2', '1']
['R2', 'R2', 'R1']


In [210]:
# Non-greedy matching ---> We can use ? sign
# Both + and * are greedy and like to capture the biggest chunk that match our pattern

B = "Hello! I am Reza! I am very happy!"
print(re.search("^H.*!", B)) # We see that this is vert greedy and captures the biggest chunk

# ? says don't be too much gready
print(re.search("^H.*?!", B))

<re.Match object; span=(0, 34), match='Hello! I am Reza! I am very happy!'>
<re.Match object; span=(0, 6), match='Hello!'>


In [220]:
C = "From R1@yahoo.com SAT 2017 12:30:17 Office PC"
print(re.findall("\S+@\S+", C))

#Fine tuning string extraction
#Parantheses () are not part of the match, but they tell where to start and stop what string to extract
print(re.findall("^From \S+@\S+", C))
print(re.findall("^From (\S+@\S+)", C))

['R1@yahoo.com']
['From R1@yahoo.com']
['R1@yahoo.com']


In [221]:
# ^ inside [] means not
# e.g., [^ ] means everything, but blank space
D = "From R2@connect.ust.hk Mon 2016 8:15:14 Home PC"
print(re.findall("@([^ ]*)", D))

['connect.ust.hk']


# Modules (save you a lot of time!)

In [ ]:
# https://docs.python.org/3/py-modindex.html
# You can go and import
# You can use pip or conda to install modules

# Classes and Objects

In [6]:
class numberofdrinks:
    x = 0 
    def moredrink(self):
        self.x += 1
        print("so far", self.x, "drink(s)")
        

print("*Sam:")
Sam = numberofdrinks()
Sam.moredrink()
Sam.moredrink()
Sam.moredrink()

print("*Jack:")
Jack = numberofdrinks()
Jack.moredrink()
Jack.moredrink()

print("*Jack and Sam:")
Jack.moredrink()
Sam.moredrink()

print("OOP is awesome!")

*Sam:
so far 1 drink(s)
so far 2 drink(s)
so far 3 drink(s)
*Jack:
so far 1 drink(s)
so far 2 drink(s)
*Jack and Sam:
so far 3 drink(s)
so far 4 drink(s)
OOP is awesome!


In [7]:
print("type is", type(Sam))
print("Methods and attributes are", dir(Sam)) # Pay attention to the method moredrink and attribute x

type is <class '__main__.numberofdrinks'>
Methods and attributes are ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'moredrink', 'x']


In [5]:
"""
Object Oriented Programming (OOP): It is a method of programming that attempts to model some process or thing in the real world as a class or object
"""
class vehichle: #A class
    pass #The pass statement is useful when you don't write the implementation of a function but you want to implement it in the future.

bus = vehichle() #An instance or an object
car = vehichle()
ship = vehichle()

In [17]:
# Objects are created, used, and discarded
# The constructor and destructor

# The constructor is typically used to set up variables. The destructor is seldom used
class solditems:
    x = 0 
    
    # This is a constructor
    def __init__(self):
        print("I am constructed.")
    
    # Similar to what we had before:
    def moresell(self):
        self.x += 1
        print("this item is sold", self.x, "times.")
        
    # This is a deconstructor    
    def __del__(self):
        print("I am deconstructed", self.x)
        
pencil = solditems()

I am constructed.


In [18]:
pencil.moresell()
pencil.moresell()
pencil.moresell()
pencil.moresell()
pencil.moresell()

this item is sold 1 times.
this item is sold 2 times.
this item is sold 3 times.
this item is sold 4 times.
this item is sold 5 times.


In [19]:
pencil = "Hi" # Pencil is now something else and does not belong to class solditems 

I am deconstructed 5


In [8]:
# Constructors can have additional parameters
class My_passport:
    born = ""
    def __init__(self, a): # Additional parameter a
        self.born = a
        print("You are born in " + self.born +".")
        
Sam = My_passport("China")

You are born in China.


In [17]:
# We can also give default values
# By the way, you might have realized all instances are independent
class My_passport:
    born = ""
    pages_used = 0
    def __init__(self, a = "Egypt", b = 0):
        self.born = a
        self.pages_used = b
        print("You are born in " + self.born +".")
    
    def newtravel(self):
        self.pages_used += 1
        print("You have traveled to", self.pages_used, "countries.")
        
Osman = My_passport()
Dan = My_passport("Iceland")
print("*************")
Dan.newtravel()
Dan.newtravel()
print("*************")
Vedat = My_passport("Turkey", 9)
Vedat.newtravel()

You are born in Egypt.
You are born in Iceland.
*************
You have traveled to 1 countries.
You have traveled to 2 countries.
*************
You are born in Turkey.
You have traveled to 10 countries.


In [26]:
class generaladd:
    def myadder(self, a, b): # self is important!!! # Do not forget!!!
        print("The result is:", a + b)
        
mysum = generaladd()
mysum.myadder(4,5)

The result is: 9


In [13]:
#Another example
class comment:
    def __init__(self, username, text = "no comments!", likes = 0): #We can set some default values
        self.username = username
        self.text = text
        self.likes = likes
Text1 = comment("Reza", "This game is awesome!", 25)
print(Text1.text)
print(Text1.likes)
Text2 = comment("Reza", "Hello gamers!")
print(Text2.text)
print(Text2.likes)
Text3 = comment("Josh")
print(Text3.text)
print(Text3.likes)

This game is awesome!
25
Hello gamers!
0
no comments!
0


In [8]:
# Object Inheritence
# A dummy example :)
class number_of_visit:
    def __init__(self, x = 0):
        self.x = x

class morevisit(number_of_visit): #morevisit is a class which extends the class of number_of_visit # It has all capabilities of the class of number_of_visit and more!
    def adder(self):
        self.x += 1
        print("So far", self.x)
        
print("Ahmad")
Ahmad = morevisit()
Ahmad.adder()
Ahmad.adder()
Ahmad.adder()

print("Ehsan")
Ehsan = morevisit(5)
Ehsan.adder()

Ahmad
So far 1
So far 2
So far 3
Ehsan
So far 6


In [17]:
class library:
    number = 0 # number of books
    def __init__(self, x):
        self.number = x
        
    def addabook(self):
        self.number += 1
        print("number of books =", self.number)
    
    def removeabook(self):
        self.number -= 1
        if self.number < 0:
            print("no book is left.")
        else:
            print("number of books =", self.number)    
        
class giftedbooks(library):
    def received(self):
        self.addabook()

        
HKUST = giftedbooks(50)
HKUST.received()
HKUST.addabook()
HKUST.removeabook()

number of books = 51
number of books = 52
number of books = 51


# Sorting an array

In [8]:
A = [12, 13, 6, 50, 80, 20, 21,96, 42, 100, 75]
def insertionsort(A):
    n = len(A)
    for j in range(1,n):
        key = A[j]
        
        i = j-1
        while i > -1 and A[i] > key:
            A[i+1] = A[i]
            i -= 1
        A[i+1] = key

In [9]:
insertionsort(A)
print(A)

[6, 12, 13, 20, 21, 42, 50, 75, 80, 96, 100]


# Basic Socket Programming

In [47]:
# This section is optional 
# One of the requirements for using the HTTP protocol is the need to send and receive data as bytes objects, instead of strings.
# the encode() and decode() methods convert strings into bytes objects and back again
# encode() and b'' are equivalent
import socket

mysock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)# No need to memorize these, I auto-completed them with tab key # This line is like a handle
mysock.connect(("www.google.com", 80)) # Host and port # port 80 is for HTTP protocol # This is where the actual connection happens # It is like dialing the phone

cmd = "GET http://www.google.com/humans.txt HTTP/1.0\r\n\r\n".encode()
mysock.send(cmd)

while True:
    data = mysock.recv(512)
    if len(data)<1:
        break
    print(data.decode(), end = "") # The default decode is to UTF-8
mysock.close()

HTTP/1.0 200 OK
Accept-Ranges: bytes
Vary: Accept-Encoding
Content-Type: text/plain
Cross-Origin-Resource-Policy: cross-origin
Content-Length: 286
Date: Wed, 18 Nov 2020 08:16:19 GMT
Expires: Wed, 18 Nov 2020 08:16:19 GMT
Cache-Control: private, max-age=0
Last-Modified: Mon, 01 Jul 2019 19:30:00 GMT
X-Content-Type-Options: nosniff
Server: sffe
X-XSS-Protection: 0

Google is built by a large team of engineers, designers, researchers, robots, and others in many different sites across the globe. It is updated continuously, and built with more tools and technologies than we can shake a stick at. If you'd like to help us out, see careers.google.com.


# urllib

In [5]:
# Since http is so common, we have a library that does all the socket work for us and makes web pages look like a file
# Instead of those socket things, we can use urllib
import urllib.request, urllib.parse, urllib.error

fhand = urllib.request.urlopen("http://www.google.com/humans.txt")
for line in fhand:
    print(line.decode().strip())

Google is built by a large team of engineers, designers, researchers, robots, and others in many different sites across the globe. It is updated continuously, and built with more tools and technologies than we can shake a stick at. If you'd like to help us out, see careers.google.com.


In [6]:
# Another example

import urllib.request, urllib.parse, urllib.error

fhand = urllib.request.urlopen("http://data.pr4e.org/romeo.txt")
for line in fhand:
    print(line.decode().strip())

But soft what light through yonder window breaks
It is the east and Juliet is the sun
Arise fair sun and kill the envious moon
Who is already sick and pale with grief


In [21]:
import urllib.request, urllib.parse, urllib.error

fhand = urllib.request.urlopen("http://data.pr4e.org/romeo.txt")

counts = dict()
for line in fhand:
    words = line.decode().split()
    for word in words:
        counts[word] = counts.get(word, 0) + 1 

# What are the four most repeated words?        
nlist = list()        
for k,v in counts.items():
    nlist.append((v,k))
tmp = sorted(nlist, reverse = True)
print(tmp[:4])


[(3, 'the'), (3, 'is'), (3, 'and'), (2, 'sun')]


In [22]:
import urllib.request, urllib.parse, urllib.error

fhand = urllib.request.urlopen("http://rhadimogavi.student.ust.hk/index.html")
for line in fhand:
    print(line.decode().strip())

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Reza Hadi Mogavi</title>

<link href="https://fonts.googleapis.com/css?family=Roboto+Slab&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Arapey&display=swap" rel="stylesheet">
<link rel="stylesheet" href="css/style.css" type="text/css" media="screen" />
<link rel="stylesheet" href="css/grid.css" type="text/css" media="screen" />
</head>

<body>
<div id="wrapper">
<table width="850" border="1">
<tr>
<td width="114"><img src="hkust.png" alt="" width="70" height="90" class="center"/></td>
<td width="314"><h6>Department of Computer Science and Engineering</h6>
<h6>Hong Kong University of Science and Technology</h6></td>
<td width="342"><h3>HADI MOGAVI, Reza (洪瑞薩)</h3><h3>Ph.D. Student</h3></td>
</tr>
</table

In [36]:
# Crawling the web
# Beautiful Soup has made life easier (https://www.crummy.com/software/BeautifulSoup/bs4/doc/)
# Installing beautifulsoup (CHECK THE INTERNET!)
import pip

if int(pip.__version__.split('.')[0])>9:
    from pip._internal import main
else:
    from pip import main
def install(package):
    main(['install', package])
    
install('BeautifulSoup4')

Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.


In [38]:
import urllib.request, urllib.parse, urllib.error
from bs4 import BeautifulSoup

myhtml = urllib.request.urlopen("http://rhadimogavi.student.ust.hk/index.html").read()
soup = BeautifulSoup(myhtml, "html.parser")

# Retrieve all of the anchor tags
tags = soup("a")
for tag in tags:
    print(tag.get("href", None)) #Use tag.get('attr') if you’re not sure attr is defined, just as you would with a Python dictionary.

#Recent_News
#Publications_1
#Teach_1
#Awards_1
https://www.cse.ust.hk/
https://www.ust.hk/
https://www.cse.ust.hk/~panhui/
https://www.cse.ust.hk/~mxj/
https://http://asonam.cpsc.ucalgary.ca/2020/
https://chi2020.acm.org/
https://link.springer.com/chapter/10.1007/978-3-030-29908-8_29
https://pdfs.semanticscholar.org/ac2c/4384e94b2cbab25568d470f3ba0d963c8319.pdf
https://www.journals.elsevier.com/computers-in-human-behavior
http://hci.cse.ust.hk/
https://www.cse.ust.hk/News/SCSA2018/
https://www.cse.ust.hk/pg/defenses/F18/rhadimogavi-27-09-2018.html
PaperShelf/HRCR.pdf


In [43]:
import urllib.request, urllib.parse, urllib.error
from bs4 import BeautifulSoup
import ssl # We will use this to avoid ssl errors

# For ignoring SSL certificate errors (you can skip reading this chunk if not interested)
ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE
 
myhtml = urllib.request.urlopen("http://rhadimogavi.student.ust.hk/index.html", context = ctx).read()

# The rest of the program would be similar to what we had before

In [20]:
import urllib.request, urllib.parse, urllib.error
from bs4 import BeautifulSoup
import ssl

# Ignore SSL certificate errors
ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

url = input("Enter - ")
html = urllib.request.urlopen(url, context = ctx).read()
soup = BeautifulSoup(html, "html.parser")

tot = 0
cnt = 0
# Retrieve all of the anchor tags
tags = soup("span")
for tag in tags:
    tot += int(tag.contents[0]) # .contents[] just gives you whats inside the tag
    cnt += 1
print("Count", cnt)
print("Sum", tot)

Enter - http://py4e-data.dr-chuck.net/comments_42.html
Count 50
Sum 2553


# XML (extensible markup language)

In [51]:
# XML is a software and hardware independent markup language used to transport and store data.
import xml.etree.ElementTree as ET

# Besides commenting, """ Hi """ can be used for indicating multiple lines of string
data = """
<users>
    <user>
        <name>Reza</name>
        <phone type='voda'>+123456789</phone>
        <email hide='No'/>
    </user>
    <user>
        <name>Mina</name>
        <phone type='intl'>+246856432</phone>
        <email hide='Yes'/>
    </user>
</users>
"""
tree = ET.fromstring(data) # It returns a tree structure of our XML (parsed)

# #Now we can access anything
lst = tree.findall("user") # The usage findall function is interesting here
print("User count =", len(lst))

print("============")
print(lst) # It is actually a list of trees
print("============")

for item in lst:
    print("Name = ", item.find("name").text)
    print("Email = ", item.find("email").get("hide"))
    print("Phone number =", item.find("phone").text)
    print("Phone type =", item.find("phone").get("type"))
    print("***********")

User count = 2
[<Element 'user' at 0x000001CE13035958>, <Element 'user' at 0x000001CE13035CC8>]
Name =  Reza
Email =  No
Phone number = +123456789
Phone type = voda
***********
Name =  Mina
Email =  Yes
Phone number = +246856432
Phone type = intl
***********


# JSON (JavaScript Object Notation)

In [7]:
# json is a lightweight format for storing and transporting data
# json seems to be more popular than XML
# You can think of json format as a tree as well

import json
# json represents data as nested lists and dictionaries
data = """ {
"name" : "Reza",
"phone" : {
    "type" : "iphone",
    "number" : "+123456895"},
"email":{
    "hide":"No"}
}
"""
# pay attention to {}s in json format # Don't forget!!!

info = json.loads(data)
print("Name =", info["name"]) # Similar to dictionary in python
print("Email =", info["email"]["hide"])

Name = Reza
Email = No


In [9]:
import json
# The following resembles a list of two dictionaries
data = """ [
{ "id" : "25516",
"condition" : "1",
"ticket" : "No"},
{ "id" : "25517",
"condition" : "2",
"ticket" : "Yes"}
]
"""

info = json.loads(data)
print("Number of users =", len(info))
print("**********")
for item in info:
    print("Id =", item["id"])
    print("Condition =", item["condition"])
    print("Ticket =", item["ticket"])
    print("************")


Number of users = 2
**********
Id = 25516
Condition = 1
Ticket = No
************
Id = 25517
Condition = 2
Ticket = Yes
************


# APIs (application programming interfaces)

In [ ]:
# e.g., Google geocoding API
# Twitter API

In [41]:
import urllib.request, urllib.parse, urllib.error
import json

#Api
api = 'http://py4e-data.dr-chuck.net/json?key=42&' 
# ? in URL acts as separator, it indicates end of URL resource path and start of query parameters.

#Input data
link = input('Enter location: ')
link = api + urllib.parse.urlencode({'address':link})
print('Retrieving', link)

html = urllib.request.urlopen(link).read().decode()
print('Retrieved', len(html), 'characters')

try:
    js = json.loads(html)
except:
    js = None

placeId = js['results'][0]['place_id']
print('Place id', placeId)

Enter location: Academy of Fine Arts Warsaw Poland
Retrieving http://py4e-data.dr-chuck.net/json?key=42&address=Academy+of+Fine+Arts+Warsaw+Poland
Retrieved 4250 characters
Place id ChIJLzAMf2DMHkcR5qCqT76Dq9M


# Database

In [15]:
#Let's create a table named book

![title](img/2020-11-29_13-59-43.png)

In [12]:
# SQL basics (Review)
# CREATE TABLE "User" ("name" TEXT, "email" TEXT)
# INSERT INTO User (name, email) VALUES ("Sara", "sara56@connect.ust.hk")
# DELETE FROM User WHERE email = "sara56@connect.ust.hk"
# UPDATE User SET name = "Gabriel" WHERE email = "ann98@gmail.com"
# SELECT * FROM User     -----> This instruction selects all the columns from table User
# SELECT * FROM User WHERE email = "Sam@yahoo.com"
# SELECT * FROM User ORDER BY name 
# SELECT COUNT(*) FROM Users # It counts the rows from table Users

# If you want to execute several lines of sql instuctions in DB browser (SQLite), add a semicolon ; at the end of each instruction, except the last one 

import sqlite3

conn = sqlite3.connect("emaildb.sqlite") # It will create this database in the same directory as these codes
cur = conn.cursor() # This is like a handle in files

# DROP TABLE [IF EXISTS] TableName
cur.execute("DROP TABLE IF EXISTS Counts")
# The DROP TABLE IF EXISTS SQL statement enables a check to see that the table exists prior to attempting the dropping (deletion) of the table. If the table does not exists then the DROP TABLE statement is not executed so no error occurs.

# For longer strings use triple quote """Hi!"""
cur.execute("""CREATE TABLE Counts (email TEXT, count INTEGER)""")

fname = input("Enter file name:")
if (len(fname) < 1):
    fname = "mbox-short.txt"
    
fh = open(fname)
for line in fh:
    if not line.startswith("From: "):
        continue # continue forces the loop to start at the next iteration while pass means "there is no code to execute here" and will continue through the remainder or the loop body. continue will jump back to the top of the loop.
    pieces = line.split()
    email = pieces[1]
    cur.execute("""SELECT count FROM Counts WHERE email = ?""", (email,)) # ? means a place holder and it helps to prevent SQL injection #(email,) is a tuple with one element
    row = cur.fetchone() # This method retrieves the next row of a query result set and returns a single sequence, or None if no more rows are available. 
    
    if row is None:
        cur.execute("""INSERT INTO Counts (email, count) VALUES (?, 1)""", (email,))
    else:
        cur.execute("""UPDATE Counts SET count = count + 1 WHERE email = ?""", (email,))

    conn.commit()
    
# Now everything is done, let's take a look at what we have done
sqlstr = "SELECT email, count FROM Counts ORDER BY count DESC LIMIT 10" # Descending order top 10

for row in cur.execute(sqlstr):
    print(str(row[0]), row[1]) # Because results are in format of a tuple
        
cur.close()

Enter file name:
cwen@iupui.edu 5
zqian@umich.edu 4
david.horwitz@uct.ac.za 4
louis@media.berkeley.edu 3
gsilver@umich.edu 3
stephen.marquard@uct.ac.za 2
rjlowe@iupui.edu 2
wagnermr@iupui.edu 1
antranig@caret.cam.ac.uk 1
gopal.ramasammycook@gmail.com 1


In [14]:
import sqlite3

conn = sqlite3.connect('orgdb.sqlite')
cur = conn.cursor()

cur.execute('DROP TABLE IF EXISTS Counts')

cur.execute('''CREATE TABLE Counts (org TEXT, count INTEGER)''')

fname = input('Enter file name: ')
if (len(fname) < 1): fname = 'mbox.txt'

fh = open(fname)
for line in fh:
    if not line.startswith('From: '): continue
    pieces = line.split()
    org = pieces[1].split("@")
    cur.execute('SELECT count FROM Counts WHERE org = ? ', (org[1],))
    row = cur.fetchone()
    if row is None:
        cur.execute('''INSERT INTO Counts (org, count)
                VALUES (?, 1)''', (org[1],))
    else:
        cur.execute('UPDATE Counts SET count = count + 1 WHERE org = ?',
                    (org[1],))
conn.commit()

# https://www.sqlite.org/lang_select.html
sqlstr = 'SELECT org, count FROM Counts ORDER BY count DESC LIMIT 10'

for row in cur.execute(sqlstr):
    print(str(row[0]), row[1])

cur.close()

Enter file name: 
iupui.edu 536
umich.edu 491
indiana.edu 178
caret.cam.ac.uk 157
vt.edu 110
uct.ac.za 96
media.berkeley.edu 56
ufp.pt 28
gmail.com 25
et.gatech.edu 17


In [ ]:
# JOIN operation
# The JOIN operation links across several tables as part of a SELECT operation
# You must tell the JOIN how to use the keys that make the connection between the tables using an ON clause 
# SELECT book.name, author.name FROM book JOIN author ON book.author_id=author.id #(foreignkey = primary key on the other table)
# Joining two tables without an ON clause gives all possible combinations of rows

# Introduction to Numpy

In [201]:
#Numpy: Numerical Computing Library
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7])
print(a)

[1 2 3 4 5 6 7]


In [204]:
#Numpy also allows multi indexing
print(a[0], a[-1], a[3])
print(a[[0, -1, 3]])

1 7 4
[1 7 4]


# Array Types

In [209]:
ia = np.array([1, 2, 3, 4])
fa = np.array([1.0, 2.0, 3.0, 4.0])
print(ia.dtype, ",", fa.dtype)

int32 , float64


In [212]:
# We can specify the types when we create arrays
fc = np.array([1, 1, 2, 3, 5], dtype = np.float)
print(fc.dtype)

float64


# Dimensions and Shapes 

In [213]:
# Let's build a matrix with four rows and three columns

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]])


print(A.shape)# This code returns the shape of the matrix

(4, 3)


In [214]:
print(A.ndim) # This returns the number of dimensions. One vertical and one horizontal

2


In [215]:
print(A.size) # The total number of elements we have in the matrix

12


In [216]:
# Let's build a cube structure
B = np.array([
    [[1, 2 , 3],[4, 5, 6]],
    [[7, 8, 9],[10, 11, 12]]
])

print(B)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [217]:
print(B.ndim)

3


In [218]:
print(B.shape)

(2, 2, 3)


In [219]:
print(B.size)

12


# Indexing and slicing matrices

In [220]:
test = np.array([
#   col0 col1 col3 
    [17, 20, 12], #row 0
    [20, 19, 10], #row 1
    [8, 13, 12]]) #row 2

print(test)

[[17 20 12]
 [20 19 10]
 [ 8 13 12]]


In [221]:
print(test[1]) # This returns row 1

[20 19 10]


In [223]:
print(test[1][1])

19


In [224]:
# A simpler way is to write like this
print(test[1, 1])

19


In [225]:
print(test[:, 1]) #column 1 from all rows

[20 19 13]


In [226]:
test[2, 2] = 20
print(test)

[[17 20 12]
 [20 19 10]
 [ 8 13 20]]


# Summary statistics

In [227]:
B = np.array([
    [1, 2, 3],
    [4, 2, 3],
    [0, 2, 5]])

print(B.sum())

22


In [228]:
print(B.mean())

2.4444444444444446


In [229]:
print(B.std())

1.4229164972072998


In [230]:
print(B.var())

2.0246913580246915


In [232]:
print(B.sum(axis=0)) # Vertical sums

[ 5  6 11]


In [233]:
print(B.sum(axis=1)) # Horizontal sums

[6 9 7]


In [234]:
print(B.mean(axis=0))

[1.66666667 2.         3.66666667]


# Broadcasting and vectorized operations

In [236]:
"""
Reminder:
range or arange?
The main difference between the two is that range is a built-in Python class,
while arange() is a function that belongs to a third-party library (NumPy).
In addition, their purposes are different! 
Generally, range is more suitable when you need to iterate using the Python for loop.
"""
a = np.arange(4)
print(a)

[0 1 2 3]


In [237]:
print(a + 10) #Adds each element with 10

[10 11 12 13]


In [238]:
print(a * 10) #Multiplies each element with 10

[ 0 10 20 30]


In [245]:
a += 1000
print(a)

[1000 1001 1002 1003]


In [246]:
a -= 1000
print(a)

[0 1 2 3]


In [249]:
b = np.arange(4)
c = a + b # Will add items correspondingly
print(c)

[0 2 4 6]


In [250]:
A = np.array ([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [251]:
print(A+1)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [252]:
print(A*2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [253]:
B = np.array ([
    [3, 30, 300],
    [1, 10, 100],
    [2, 20, 200]])
print(A*B) # This produces element-wise multiplication

[[   3   60  900]
 [   4   50  600]
 [  14  160 1800]]


In [254]:
C = np.array ([
    [3, 30],
    [1, 10]])
print(A*C) # This will result in an error

ValueError: operands could not be broadcast together with shapes (3,3) (2,2) 

In [255]:
D = np.array([
    [1000],
    [1000],
    [1000]
])

print(A*D)

[[1000 2000 3000]
 [4000 5000 6000]
 [7000 8000 9000]]


In [256]:
E = np.array([
    [10, 10, 10]
])
print(A*E)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [101]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [103]:
cal = A.sum(axis = 0) #If axis = 0, python sums vertically
print(cal)

[ 59.  239.  155.4  76.9]


In [104]:
cal2 = A.sum(axis = 1)#If axis = 1, python sums horizontally
print(cal2)

[128.4 165.2 236.7]


In [105]:
percentage = 100*A/cal.reshape(1,4) # We could have avoided writing reshape(1,4), because cal is laready in that shape. It is kind of to make sure everything is correct!!!!
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


# Numpy and Vectorization

In [69]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) # This is an array genererated with numpy

In [70]:
print(type(a))

<class 'numpy.ndarray'>


In [71]:
print(a) # printing the array

[ 1  2  3  4  5  6  7  8  9 10]


In [85]:
# vectorization means that we don't use for loops
import time 

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b) # similar to (w^T)* x
toc = time.time()

print("vectorized version: ", (toc-tic)*1000, "ms\n")
print("c = ", c)

vectorized version:  1.0001659393310547 ms

c =  250245.2227706333


In [86]:
c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print("for loop version: ", (toc-tic)*1000, "ms\n")
print("c = ", c)

for loop version:  593.4576988220215 ms

c =  250245.22277063166


# Numpy

In [87]:
import numpy as np

z = np.zeros((5,3)) # 5 rows and 3 columns
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [91]:
o = np.ones((2,4)) # 2 rows and 4 columns
print(o)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [93]:
# A bad approach
import math

a=np.array([0, 1, 2, 3, 4, 5])
u=np.zeros((6, 1))

for i in range(6):
    u[i] = math.exp(a[i])

print(u)

[[  1.        ]
 [  2.71828183]
 [  7.3890561 ]
 [ 20.08553692]
 [ 54.59815003]
 [148.4131591 ]]


In [100]:
# A good approach
# Instead, we could write
u = np.exp(a) # This is vectorization because we don't use for loops anymore
print(u)

[  1.           2.71828183   7.3890561   20.08553692  54.59815003
 148.4131591 ]


# Suggestions 

In [110]:
a = np.random.randn(5)# random gaussian numbers 
print(a)

[-1.80155712 -0.77515702 -0.6121915  -0.3747502  -0.2387494 ]


In [113]:
print(a.shape) # You clearly see that this is not a vector # Do not use rank 1 arrays like this!!!

(5,)


In [114]:
print(a.T)# We see that the transpose is the same

[-1.80155712 -0.77515702 -0.6121915  -0.3747502  -0.2387494 ]


In [115]:
# So, the suggestion is to avoid creating things that have shape like (5,)
# Make clear vectors
b = np.random.randn(5, 1) # Like this
print(b)

[[-0.84471783]
 [ 1.982594  ]
 [-0.37981728]
 [ 0.03902724]
 [ 0.5157601 ]]


In [116]:
print(b.shape)

(5, 1)


In [117]:
print(b.T)# Now, we can create this beautiful transpose

[[-0.84471783  1.982594   -0.37981728  0.03902724  0.5157601 ]]


In [127]:
# What can we do to fix a?
a = a.reshape(5,1)
print(a)

[[-1.80155712]
 [-0.77515702]
 [-0.6121915 ]
 [-0.3747502 ]
 [-0.2387494 ]]


In [129]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1) # Broadcasting happends here too!!!
c = a*b
print(c)

[[-0.02170128  0.22850884 -0.09742981]
 [ 0.37566268 -0.09725285  0.11940799]
 [ 0.239979   -0.03239958 -0.40649077]]


# Pandas

In [126]:
# I want to start using pandas
import pandas as pd
import numpy as np

In [128]:
# Series
# You can think of it as a cross btween list and dictionary
# As you might expect, you can create a series by passing in a list of values
# When you do this, pandas automatically assigns assigns an index starting from zero, and sets the name of the series to None

students = ["Reza", "Jim", "Mitra", "Ann"]

pd.Series(students) #This will create a series 

0     Reza
1      Jim
2    Mitra
3      Ann
dtype: object

In [130]:
Grades = [85, 90, 67, 100]

pd.Series(Grades) # This will create a series

0     85
1     90
2     67
3    100
dtype: int64

In [132]:
#How does pandas handle missing data?
students = ["Naghmeh", "Nazanin", "Asal", None]

pd.Series(students)

0    Naghmeh
1    Nazanin
2       Asal
3       None
dtype: object

In [134]:
Grades = [90, 100, None, 80]

pd.Series(Grades) #NaN means not a number. To show NaN, it changed all data types to float

0     90.0
1    100.0
2      NaN
3     80.0
dtype: float64

In [135]:
# We need to use a special function to check for the presence of a nan
print(np.isnan(np.nan))

True


In [137]:
# However:
print(np.nan == None)
print(np.nan == np.nan)
# So the moral lesson is to always use np.isnan() to check for the existence of "not a number"

False
False


In [141]:
# A series can be created directly from a dictionary data
student_course = {
    "Reza" : "Chemistry",
    "Tina" : "IT",
    "Sam" : "Math",
    "Mary" : "Geography"}

s = pd.Series(student_course)

In [142]:
s.index # You can see that pandas treats everything like numpy objects

Index(['Reza', 'Tina', 'Sam', 'Mary'], dtype='object')

In [148]:
# A list of tuples
student_color = [("Reza" , "Blue"), ("Sian" , "Brown"), ("Kim" , "Black"), ("Rose" , "Orange"),("Sam" , "Red")]

pd.Series(student_color) 

0      (Reza, Blue)
1     (Sian, Brown)
2      (Kim, Black)
3    (Rose, Orange)
4        (Sam, Red)
dtype: object

In [150]:
# We can separate index creation from data passing

s1 = pd.Series([12, 13, 14, 20, 8], index = ["I1", "I2", "I3", "I4", "I5"])

print(s1)

I1    12
I2    13
I3    14
I4    20
I5     8
dtype: int64


In [152]:
# What if the index is not alligned with dictionary key
student_grade = {
    "Tom" : 80,
    "Tina" : 98,
    "Sina" : 52}

pd.Series(student_grade, index = ["Tom", "I2", "Sina"])

Tom     80.0
I2       NaN
Sina    52.0
dtype: float64